import type {ChapterBoard} from './types';

/**
 * Bảng phân cảnh. Mỗi shot khai báo `say` — mẩu lời bình mà nó minh hoạ.
 * Thời điểm cắt lấy từ chính câu đó, nên hình LUÔN khớp tiếng.
 * Đây là thứ thay cho việc sinh shot tự động: máy không đoán được
 * "câu này nên hiện cái gì", chỉ người viết mới biết.
 */
export const BOARD: ChapterBoard[] = [
  {
    id: 'hook',
    shots: [
      {
        say: 'Ê.',
        place: 'quan',
        cut: 'can',
        nhin: [560, 560],
        actors: [{who: 'teo', mood: 'vui', x: 560, vi: 1}],
        sfx: 'pop',
      },
      {
        say: 'Bát phở năm hai nghìn không trăm mười lăm',
        place: 'quan',
        cut: 'trung',
        actors: [{who: 'teo', mood: 'ok', x: 470, vi: 1}],
        props: [{p: 'pho', x: 1290, y: 790, s: 1.15}],
        enter: 'whipL',
        sfx: 'whoosh-short',
      },
      {
        say: 'ba mươi nghìn',
        place: 'quan',
        cut: 'sat',
        nhin: [1290, 640],
        props: [
          {p: 'pho', x: 1290, y: 790, s: 1.15},
          {p: 'gia', x: 1250, y: 470, text: '30.000₫', mau: 'xanh'},
        ],
        enter: 'zoom',
        sfx: 'ding',
      },
      {
        say: 'Bát phở bây giờ',
        place: 'quan',
        cut: 'trung',
        props: [{p: 'pho', x: 1190, y: 790, s: 1.15}],
        actors: [{who: 'phong', size: 0.15, x: 480, y: 640}],
        enter: 'whipR',
        sfx: 'whoosh-up',
      },
      {
        say: 'năm mươi nghìn',
        place: 'quan',
        cut: 'sat',
        nhin: [1190, 630],
        props: [
          {p: 'pho', x: 1190, y: 790, s: 1.15},
          {p: 'gia', x: 1150, y: 450, text: '50.000₫', mau: 'do'},
        ],
        enter: 'no',
        sfx: 'boom',
        dap: true,
      },
      {
        say: 'Mà thịt thì ít hơn',
        place: 'quan',
        cut: 'sat',
        nhin: [1150, 720],
        props: [{p: 'pho', x: 1150, y: 760, s: 1.5, thit: 1}],
        enter: 'cut',
        sfx: 'pop-high',
      },
      {
        say: 'và cái ghế nhựa thì vẫn gãy y như cũ',
        place: 'quan',
        cut: 'can',
        nhin: [900, 800],
        props: [{p: 'ghe', x: 900, y: 880, s: 2.2}],
        enter: 'cut',
        sfx: 'thud',
      },
      {
        say: 'Mày nghĩ ông bán phở tham à?',
        place: 'quan',
        cut: 'can',
        nhin: [700, 560],
        actors: [{who: 'teo', mood: 'nghi', x: 700, vi: 0.9}],
        enter: 'truot',
        sfx: 'whoosh-short',
      },
      {
        say: 'Đéo phải.',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'khung', text: 'ĐÉO PHẢI.'},
        enter: 'no',
        sfx: 'boom',
        dap: true,
      },
      {
        say: 'Ông ấy cũng đang chửi y như mày.',
        place: 'quan',
        cut: 'trung',
        actors: [
          {who: 'teo', mood: 'tuc', x: 560, vi: 0.85},
          {who: 'teo', mood: 'tuc', x: 1340, flip: true, vi: 0.85},
        ],
        enter: 'cut',
        sfx: 'pop',
      },
    ],
  },

  {
    id: 'dinh-nghia',
    shots: [
      {
        say: 'Đây là chỗ chín mươi phần trăm người ta hiểu sai.',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'so', value: 90, suffix: '%', label: 'hiểu sai chỗ này'},
        enter: 'zoom',
        sfx: 'riser',
      },
      {
        say: 'Lạm phát không phải là giá tăng.',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'khung', text: 'KHÔNG phải giá tăng'},
        enter: 'whipL',
        sfx: 'whoosh-short',
      },
      {
        say: 'Lạm phát là tiền của mày co lại.',
        place: 'phong',
        cut: 'trung',
        actors: [{who: 'teo', mood: 'soc', x: 620, vi: 0.5, cam: 'tien'}],
        props: [{p: 'tien', x: 1320, y: 500, s: 1.6, n: 1}],
        overlay: {o: 'thuatngu', term: 'LẠM PHÁT', nghia: 'sức mua của đồng tiền giảm đi'},
        enter: 'no',
        sfx: 'deflate',
        dap: true,
      },
      {
        say: 'Cái bát phở vẫn là bát phở đấy',
        place: 'phong',
        cut: 'can',
        nhin: [1200, 720],
        props: [{p: 'pho', x: 1200, y: 780, s: 1.2}],
        enter: 'cut',
        sfx: 'pop',
      },
      {
        say: 'Thứ thay đổi là tờ tiền trong ví mày.',
        place: 'phong',
        cut: 'sat',
        nhin: [700, 780],
        actors: [{who: 'teo', mood: 'nghi', x: 620, vi: 0.35}],
        enter: 'zoom',
        sfx: 'whoosh-down',
      },
      {
        say: 'nhưng nó đã âm thầm gầy đi.',
        place: 'phong',
        cut: 'trung',
        actors: [{who: 'teo', mood: 'khoc', x: 620, vi: 0.15}],
        props: [{p: 'tien', x: 1320, y: 560, s: 0.7, n: 1}],
        enter: 'cut',
        sfx: 'deflate',
      },
      {
        say: 'Tiền không mất giá trong một đêm.',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'khung', text: 'không mất giá trong một đêm'},
        enter: 'truot',
        sfx: 'whoosh-short',
      },
      {
        say: 'Nó mất giá như tóc mày rụng.',
        place: 'phong',
        cut: 'can',
        nhin: [700, 520],
        actors: [{who: 'teo', mood: 'chet', x: 700, vi: 0.1}],
        overlay: {o: 'meme', src: 'meme/cheems.jpg', cap: 'mỗi ngày một ít'},
        enter: 'whipR',
        sfx: 'pop-high',
      },
      {
        say: 'và đến lúc mày soi gương thì đã muộn.',
        place: 'phong',
        cut: 'trung',
        actors: [
          {who: 'teo', mood: 'khoc', x: 620, vi: 0},
          {who: 'phong', size: 0.3, x: 1420, y: 640},
        ],
        enter: 'cut',
        sfx: 'inflate',
      },
    ],
  },

  {
    id: 'in-tien',
    shots: [
      {
        say: 'Vậy tiền teo vì cái gì?',
        place: 'kho',
        cut: 'can',
        nhin: [640, 560],
        actors: [{who: 'teo', mood: 'nghi', x: 640, vi: 0.4}],
        enter: 'whipL',
        sfx: 'whoosh-short',
      },
      {
        say: 'Vì có quá nhiều tiền.',
        place: 'kho',
        cut: 'rong',
        props: [{p: 'mayin', x: 520, y: 720, s: 1.3}],
        actors: [{who: 'phong', size: 0.35, x: 1440, y: 620, mood: 'doi'}],
        enter: 'no',
        sfx: 'cash',
        dap: true,
      },
      {
        say: 'Tưởng tượng cả nước có mười cái bánh mì',
        place: 'kho',
        cut: 'trung',
        props: [{p: 'banhmi', x: 960, y: 700, s: 1.5, n: 10}],
        enter: 'cut',
        sfx: 'pop',
      },
      {
        say: 'và một trăm nghìn đồng.',
        place: 'kho',
        cut: 'trung',
        props: [
          {p: 'banhmi', x: 640, y: 700, s: 1.2, n: 10},
          {p: 'tien', x: 1400, y: 760, s: 1.2, n: 4},
        ],
        enter: 'truot',
        sfx: 'cash',
      },
      {
        say: 'Mỗi cái bánh mì mười nghìn.',
        place: 'kho',
        cut: 'can',
        nhin: [960, 640],
        props: [{p: 'gia', x: 960, y: 560, text: '10.000₫', mau: 'xanh'}],
        enter: 'zoom',
        sfx: 'ding',
      },
      {
        say: 'Giờ nhà nước in thêm, thành một triệu đồng.',
        place: 'kho',
        cut: 'rong',
        props: [{p: 'mayin', x: 500, y: 720, s: 1.3}],
        actors: [{who: 'phong', size: 0.5, x: 1400, y: 560, mood: 'doi'}],
        enter: 'no',
        sfx: 'inflate',
        dap: true,
      },
      {
        say: 'Nhưng bánh mì thì vẫn mười cái',
        place: 'kho',
        cut: 'can',
        nhin: [960, 700],
        props: [{p: 'banhmi', x: 960, y: 700, s: 1.6, n: 10}],
        enter: 'cut',
        sfx: 'pop-high',
      },
      {
        say: 'vì in tiền thì nhanh, còn trồng lúa thì phải chờ ba tháng.',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'khung', text: 'in tiền: 1 giây', sub: 'trồng lúa: 3 tháng'},
        enter: 'whipR',
        sfx: 'whoosh-up',
      },
      {
        say: 'Kết quả?',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'khung', text: 'KẾT QUẢ?'},
        enter: 'zoom',
        sfx: 'riser',
      },
      {
        say: 'Mỗi cái bánh mì một trăm nghìn.',
        place: 'kho',
        cut: 'can',
        nhin: [960, 620],
        props: [{p: 'gia', x: 960, y: 560, text: '100.000₫', mau: 'do'}],
        enter: 'no',
        sfx: 'boom',
        dap: true,
      },
      {
        say: 'Mày không giàu lên.',
        place: 'kho',
        cut: 'can',
        nhin: [700, 560],
        actors: [{who: 'teo', mood: 'chet', x: 700, vi: 0.3}],
        enter: 'cut',
        sfx: 'thud',
      },
      {
        say: 'Chỉ có con số là to ra thôi.',
        place: 'kho',
        cut: 'trung',
        actors: [{who: 'phong', size: 0.55, x: 1300, y: 540, mood: 'nham'}],
        enter: 'truot',
        sfx: 'inflate',
      },
      {
        say: 'Đấy, gọi là lạm phát.',
        place: 'kho',
        cut: 'trung',
        actors: [{who: 'phong', size: 0.55, x: 1300, y: 540, mood: 'cuoi'}],
        overlay: {o: 'thuatngu', term: 'CUNG TIỀN', nghia: 'tổng lượng tiền đang lưu thông'},
        enter: 'cut',
        sfx: 'ding',
      },
    ],
  },

  {
    id: 'zimbabwe',
    shots: [
      {
        say: 'Muốn xem nó đi xa đến đâu à?',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'khung', text: 'ĐI XA ĐẾN ĐÂU?'},
        enter: 'whipL',
        sfx: 'riser',
      },
      {
        say: 'Zimbabwe',
        place: 'do',
        cut: 'rong',
        overlay: {o: 'khung', text: 'ZIMBABWE', sub: '2008'},
        enter: 'no',
        sfx: 'boom',
        dap: true,
      },
      {
        say: 'Chính phủ in tiền như in tờ rơi.',
        place: 'do',
        cut: 'trung',
        props: [{p: 'mayin', x: 600, y: 760, s: 1.4}],
        enter: 'cut',
        sfx: 'cash',
      },
      {
        say: 'Lạm phát chạm mốc bảy mươi chín tỷ phần trăm.',
        place: 'do',
        cut: 'rong',
        overlay: {o: 'so', value: 79000000000, suffix: '%', label: 'trong MỘT tháng'},
        enter: 'zoom',
        sfx: 'riser',
        dap: true,
      },
      {
        say: 'Giá cả tăng gấp đôi sau mỗi hai mươi tư tiếng.',
        place: 'do',
        cut: 'trung',
        actors: [{who: 'phong', size: 0.8, x: 960, y: 540, mood: 'doi'}],
        enter: 'no',
        sfx: 'inflate',
      },
      {
        say: 'vì đến chiều là mất một nửa.',
        place: 'do',
        cut: 'can',
        nhin: [760, 620],
        actors: [{who: 'teo', mood: 'soc', x: 760, vi: 0.05}],
        enter: 'cut',
        sfx: 'deflate',
      },
      {
        say: 'Họ in ra tờ một trăm nghìn tỷ đô la.',
        place: 'do',
        cut: 'rong',
        overlay: {o: 'khung', text: '$100.000.000.000.000'},
        enter: 'whipR',
        sfx: 'cash',
      },
      {
        say: 'Mua được đúng ba quả trứng.',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'khung', text: '= 3 quả trứng'},
        enter: 'zoom',
        sfx: 'pop-high',
        dap: true,
      },
      {
        say: 'Đm, mỉa mai vãi.',
        place: 'do',
        cut: 'can',
        nhin: [760, 600],
        actors: [{who: 'teo', mood: 'chet', x: 760, vi: 0}],
        overlay: {o: 'meme', src: 'meme/khaby-lame.jpg', cap: 'ờ...'},
        enter: 'cut',
        sfx: 'thud',
      },
    ],
  },

  {
    id: 'shrinkflation',
    shots: [
      {
        say: 'Nhưng mà doanh nghiệp nó khôn hơn thế.',
        place: 'sieuthi',
        cut: 'trung',
        actors: [{who: 'sep', x: 1340, s: 1, flip: true}],
        enter: 'whipL',
        sfx: 'whoosh-short',
      },
      {
        say: 'Nó biết mày nhạy cảm với giá.',
        place: 'sieuthi',
        cut: 'can',
        nhin: [620, 560],
        actors: [{who: 'teo', mood: 'nghi', x: 620, vi: 0.5}],
        enter: 'cut',
        sfx: 'pop',
      },
      {
        say: 'là mày nhớ liền, mày chửi liền.',
        place: 'sieuthi',
        cut: 'can',
        nhin: [620, 560],
        actors: [{who: 'teo', mood: 'tuc', x: 620, vi: 0.5}],
        enter: 'cut',
        sfx: 'pop-high',
      },
      {
        say: 'Nên nó không tăng giá.',
        place: 'sieuthi',
        cut: 'trung',
        props: [{p: 'gia', x: 1200, y: 480, text: '10.000₫', mau: 'xanh'}],
        enter: 'truot',
        sfx: 'ding',
      },
      {
        say: 'và bóp gói bim bim từ tám mươi gram xuống sáu mươi gram.',
        place: 'sieuthi',
        cut: 'trung',
        props: [{p: 'bimbim', x: 1240, y: 560, s: 1.2, phong: 1.3, gram: 60}],
        overlay: {o: 'thuatngu', term: 'SHRINKFLATION', nghia: 'giữ giá, bóp nhỏ khối lượng'},
        enter: 'no',
        sfx: 'deflate',
        dap: true,
      },
      {
        say: 'và bên trong thì bảy mươi phần trăm là khí ni tơ.',
        place: 'sieuthi',
        cut: 'sat',
        nhin: [1240, 560],
        props: [{p: 'bimbim', x: 1240, y: 560, s: 1.2, phong: 1.35, gram: 60}],
        overlay: {o: 'so', value: 70, suffix: '%', label: 'là khí'},
        enter: 'zoom',
        sfx: 'inflate',
      },
      {
        say: 'Mày mở ra, nghe cái bụp',
        place: 'sieuthi',
        cut: 'can',
        nhin: [660, 560],
        actors: [{who: 'teo', mood: 'ngo', x: 660, vi: 0.4}],
        enter: 'cut',
        sfx: 'pop',
        dap: true,
      },
      {
        say: 'rồi nhìn vào và tự hỏi cuộc đời mình đã sai ở đâu.',
        place: 'sieuthi',
        cut: 'can',
        nhin: [660, 560],
        actors: [{who: 'teo', mood: 'chet', x: 660, vi: 0.35}],
        overlay: {o: 'meme', src: 'meme/pooh.png', cap: 'trả đủ tiền, nhận nửa gói'},
        enter: 'cut',
        sfx: 'thud',
      },
      {
        say: 'Lạm phát mặc áo tàng hình.',
        place: 'sieuthi',
        cut: 'trung',
        actors: [{who: 'phong', size: 0.45, x: 1300, y: 600, mood: 'nham'}],
        enter: 'truot',
        sfx: 'whoosh-down',
      },
    ],
  },

  {
    id: 'skimpflation',
    shots: [
      {
        say: 'Còn một chiêu nữa, còn khó bắt hơn.',
        place: 'sieuthi',
        cut: 'can',
        nhin: [640, 560],
        actors: [{who: 'teo', mood: 'nghi', x: 640, vi: 0.35}],
        enter: 'whipL',
        sfx: 'whoosh-short',
      },
      {
        say: 'Giá giữ nguyên',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'thuatngu', term: 'SKIMPFLATION', nghia: 'giữ giá, giữ lượng, hạ chất lượng'},
        enter: 'no',
        sfx: 'ding',
        dap: true,
      },
      {
        say: 'Sô cô la bớt ca cao, thêm dầu thực vật.',
        place: 'sieuthi',
        cut: 'trung',
        props: [{p: 'socola', x: 1240, y: 520, s: 1.2, cacao: 22}],
        enter: 'zoom',
        sfx: 'pop',
      },
      {
        say: 'Nước cam từ ép nguyên chất thành hương cam tổng hợp.',
        place: 'sieuthi',
        cut: 'can',
        nhin: [1240, 520],
        props: [{p: 'socola', x: 1240, y: 520, s: 1.2, cacao: 22}],
        enter: 'cut',
        sfx: 'pop-high',
      },
      {
        say: 'Khách sạn vẫn giá đó nhưng bỏ dọn phòng hằng ngày',
        place: 'phong',
        cut: 'rong',
        enter: 'truot',
        sfx: 'whoosh-down',
      },
      {
        say: 'gọi là bảo vệ môi trường.',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'khung', text: '"bảo vệ môi trường"'},
        enter: 'cut',
        sfx: 'ding',
      },
      {
        say: 'thay bằng con chatbot ngu hơn cả mày lúc bốn giờ sáng.',
        place: 'phong',
        cut: 'can',
        nhin: [700, 560],
        actors: [{who: 'teo', mood: 'chet', x: 700, vi: 0.3}],
        overlay: {o: 'meme', src: 'meme/woman-cat.jpg', cap: '"xin lỗi, tôi chưa hiểu"'},
        enter: 'whipR',
        sfx: 'thud',
      },
      {
        say: 'Mày vẫn trả đủ, chỉ là mày nhận về ít hơn',
        place: 'phong',
        cut: 'trung',
        actors: [
          {who: 'teo', mood: 'tuc', x: 620, vi: 0.2},
          {who: 'phong', size: 0.5, x: 1360, y: 600, mood: 'nham'},
        ],
        enter: 'cut',
        sfx: 'deflate',
      },
      {
        say: 'và không ai đưa cho mày cái hoá đơn nào ghi điều đó cả.',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'khung', text: 'không ai gửi mày hoá đơn'},
        enter: 'zoom',
        sfx: 'boom',
        dap: true,
      },
    ],
  },

  {
    id: 'luong',
    shots: [
      {
        say: 'Đây, đoạn quan trọng nhất, nghe cho kỹ.',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'khung', text: 'NGHE CHO KỸ'},
        enter: 'no',
        sfx: 'riser',
        dap: true,
      },
      {
        say: 'Sếp gọi mày vào phòng, mặt long trọng',
        place: 'phong',
        cut: 'rong',
        actors: [
          {who: 'sep', x: 1300, s: 1, flip: true},
          {who: 'teo', mood: 'ok', x: 620, vi: 0.6},
        ],
        enter: 'whipL',
        sfx: 'whoosh-short',
      },
      {
        say: 'nhưng vẫn cố tăng lương cho em bảy phần trăm.',
        place: 'phong',
        cut: 'trung',
        actors: [{who: 'sep', x: 1300, s: 1, flip: true}],
        props: [{p: 'bangluong', x: 900, y: 480, s: 1.1, tang: '+7%', gia: '—'}],
        enter: 'cut',
        sfx: 'ding',
      },
      {
        say: 'Mày cảm động. Mày cảm ơn.',
        place: 'phong',
        cut: 'can',
        nhin: [620, 560],
        actors: [{who: 'teo', mood: 'vui', x: 620, vi: 0.6}],
        enter: 'zoom',
        sfx: 'pop',
      },
      {
        say: 'Mày về khoe người yêu.',
        place: 'pho',
        cut: 'trung',
        actors: [{who: 'teo', mood: 'vui', x: 760, vi: 0.6}],
        enter: 'truot',
        sfx: 'pop-high',
      },
      {
        say: 'Nhưng lạm phát năm đó là mười phần trăm.',
        place: 'phong',
        cut: 'rong',
        props: [{p: 'bangluong', x: 900, y: 480, s: 1.2, tang: '+7%', gia: '+10%'}],
        actors: [{who: 'phong', size: 0.55, x: 1500, y: 560, mood: 'nham'}],
        enter: 'no',
        sfx: 'boom',
        dap: true,
      },
      {
        say: 'Nghĩa là sức mua của mày vừa giảm ba phần trăm.',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'so', value: -3, suffix: '%', label: 'sức mua thực tế'},
        enter: 'zoom',
        sfx: 'deflate',
      },
      {
        say: 'Mày vừa bị giảm lương, và mày vừa nói cảm ơn vì điều đó.',
        place: 'phong',
        cut: 'can',
        nhin: [620, 560],
        actors: [{who: 'teo', mood: 'chet', x: 620, vi: 0.15}],
        overlay: {o: 'meme', src: 'meme/pooh.png', cap: 'cảm ơn sếp ạ'},
        enter: 'cut',
        sfx: 'thud',
        dap: true,
      },
      {
        say: 'Cái con số trên hợp đồng gọi là lương danh nghĩa.',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'thuatngu', term: 'LƯƠNG DANH NGHĨA', nghia: 'con số ghi trên hợp đồng'},
        enter: 'whipR',
        sfx: 'ding',
      },
      {
        say: 'Cái mà nó mua được mới gọi là lương thực tế.',
        place: 'trong',
        cut: 'rong',
        overlay: {o: 'thuatngu', term: 'LƯƠNG THỰC TẾ', nghia: 'số hàng con số đó mua được'},
        enter: 'truot',
        sfx: 'ding',
      },
      {
        say: 'tất cả bọn nó đều tính bằng lương thực tế.',
        place: 'pho',
        cut: 'trung',
        actors: [{who: 'sep', x: 1280, s: 1, flip: true}],
        enter: 'cut',
        sfx: 'whoosh-down',
      },
      {
        say: 'Chỉ có mày là vẫn đang tính bằng con số.',
        place: 'pho',
        cut: 'can',
        nhin: [700, 560],
        actors: [{who: 'teo', mood: 'khoc', x: 700, vi: 0.05}],
        enter: 'zoom',
        sfx: 'thud',
        dap: true,
      },
    ],
  },
];
